# Generated by Django 3.0.7 on 2020-06-30 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtube',
            name='sharedon',
        ),
    ]
