# Generated by Django 3.0.7 on 2020-06-30 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0004_auto_20200629_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='RTMP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField(blank=True, null=True)),
                ('source_stream_name', models.CharField(max_length=512)),
                ('destination_application_name', models.CharField(max_length=512)),
                ('destination_host', models.CharField(max_length=512)),
                ('destination_port', models.IntegerField()),
                ('destination_stream_name', models.CharField(max_length=512)),
                ('destination_username', models.CharField(max_length=512)),
                ('destination_password', models.CharField(max_length=512)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.Application')),
            ],
        ),
    ]
