# Generated by Django 3.0.7 on 2020-06-30 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtmp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rtmp',
            name='destination_password',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='rtmp',
            name='destination_username',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
