# Generated by Django 3.0.7 on 2020-06-30 22:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rtmp', '0003_auto_20200630_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='rtmp',
            name='enable_schedule',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rtmp',
            name='end_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='rtmp',
            name='start_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
