# Generated by Django 3.0.7 on 2020-06-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebook',
            name='share_on',
            field=models.CharField(choices=[('TIMELINE', 'Time Line'), ('PAGE', 'Page')], default='TIMELINE', max_length=9),
        ),
    ]
