# Generated by Django 3.0.7 on 2020-06-30 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0002_facebook_share_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facebook',
            old_name='share_on',
            new_name='sharedon',
        ),
    ]
