# Generated by Django 3.0.7 on 2020-06-30 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0003_auto_20200630_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebook',
            name='privacy',
            field=models.CharField(choices=[('ONLYME', 'Only Me'), ('FRIENDS', 'Friends'), ('FRIENDSOFFRIENDS', 'Friends of Friends'), ('PUBLIC', 'Public')], default='ONLYME', max_length=128),
        ),
    ]
