# Generated by Django 3.0.7 on 2020-06-30 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0004_facebook_privacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebook',
            name='facebook_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facebook',
            name='facebook_title',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='facebook',
            name='send_continuous_live',
            field=models.BooleanField(default=False),
        ),
    ]
