# Generated by Django 3.0.7 on 2020-06-30 22:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0005_auto_20200630_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebook',
            name='enable_schedule',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='facebook',
            name='end_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='facebook',
            name='start_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
