# Generated by Django 3.0.7 on 2020-06-30 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0006_auto_20200630_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facebook',
            name='destination_password',
        ),
        migrations.RemoveField(
            model_name='facebook',
            name='destination_username',
        ),
    ]
