# Generated by Django 3.0.7 on 2020-06-29 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='type',
            field=models.CharField(choices=[('Live', '1'), ('VOD', '2')], default='Live', max_length=9),
        ),
    ]
