# Generated by Django 3.0.7 on 2020-06-29 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='type',
            field=models.CharField(choices=[('LIVE', 'Live'), ('VOD', 'VOD')], default='LIVE', max_length=9),
        ),
    ]
