# Generated by Django 3.0.7 on 2020-07-04 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_auto_20200704_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
