# Generated by Django 3.0.7 on 2020-07-13 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_auto_20200704_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='app_config_path',
            field=models.CharField(default='/usr/local/iohub/publisher/applications/', max_length=32),
        ),
        migrations.AddField(
            model_name='application',
            name='hls_fragment',
            field=models.CharField(default='3', max_length=8),
        ),
        migrations.AddField(
            model_name='application',
            name='hls_path',
            field=models.CharField(default='/mnt/hls/', max_length=32),
        ),
        migrations.AddField(
            model_name='application',
            name='hls_playlist_length',
            field=models.CharField(default='60', max_length=8),
        ),
        migrations.AddField(
            model_name='application',
            name='hls_port',
            field=models.CharField(default='8080', max_length=8),
        ),
        migrations.AddField(
            model_name='application',
            name='rtmp_port',
            field=models.CharField(default='1935', max_length=8),
        ),
    ]
