# Generated by Django 3.0.7 on 2020-07-13 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_auto_20200713_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='app_config_path',
            field=models.CharField(default='/usr/local/iohub/publisher/applications/', max_length=512),
        ),
        migrations.AlterField(
            model_name='application',
            name='hls_path',
            field=models.CharField(default='/mnt/hls/', max_length=512),
        ),
    ]
