# Generated by Django 3.0.7 on 2020-07-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_auto_20200713_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='app_config_path',
            field=models.CharField(default='/usr/local/iohub/publisher/applications/conf/', max_length=512),
        ),
    ]
