# Generated by Django 3.0.7 on 2020-07-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_auto_20200718_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='app_config_path',
            field=models.CharField(default='./applications/conf/', max_length=512),
        ),
    ]
