# Generated by Django 3.0.7 on 2020-06-30 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0002_rtmp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RTMP',
        ),
    ]
